### PR TITLE
Add .env file

### PR DESCRIPTION
**Pull request by gylaz**
Why:

* This file should be checked in with good, safe defaults,
  and `.env.local` should be used to override per machine.

### CODE REVIEW

**Comment by teoljungberg** [comment]
I'm into it

**Comment by gabebw** [comment]
This should be copied in `./bin/setup`, like `[ ! -f .env.local ] && cp .env .env.local`

**Comment by gylaz** [comment]
@gabebw Can you explain your opinion a bit?

`.env` provides safe defaults that the user can run with. In this case `.env.local` is not necessary, and the first line of `.env` instructs on what to do.

**Comment by gabebw** [comment]
Oh I see now - there's nothing private in `.env`. I retract my opinion.

**Pull request merged**
